Vagrant.configure("2") do |config|
  config.vm.box = "bento/ubuntu-18.04"
  config.vm.network "forwarded_port", guest: 443, host: 443
  config.vm.network "forwarded_port", guest: 389, host: 389
  config.vm.network "forwarded_port", guest: 9443, host: 9443
  config.vm.network "forwarded_port", guest: 636, host: 636
  config.vm.provision "shell", inline: "sudo apt --assume-yes  install docker.io"
  config.vm.provision "shell", inline: "sudo apt-get install docker-compose -y" 
  config.vm.provision "shell", inline: "sudo systemctl start docker"
  config.vm.provision "shell", inline: "sudo systemctl enable docker"
  config.vm.provision "shell", inline: "sudo apt-get install ansible -y" 
  config.vm.provision "shell", inline: "sudo apt-get install python-pip -y" 
  config.vm.provision "shell", inline: "sudo pip install ibmsecurity" 
  config.vm.provision "shell", inline: "git clone https://github.com/hennesb/all-things-isam.git" 
end