version: '3'
services:
#
# Security Access Manager Containers
#
  isam-config:
    image: ibmcom/isam:9.0.7.1_IF4
    hostname: isam-conf
    environment:
      - SERVICE=config
      - CONTAINER_TIMEZONE=${TIMEZONE}
    volumes:
      - /tmp/isam-dev-lab/isam-volume:/var/shared
      - /tmp/isam-dev-lab/isam-logs/conf:/var/application.logs
    ports:
      - ${CONFIG_HTTPS_PORT}:9443
    depends_on:
      - isam-ldap
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE

  isam-webseal:
    image: ibmcom/isam:9.0.7.1_IF4
    hostname: isam-webseal
    environment:
      - SERVICE=webseal
      - INSTANCE=${WEBSEAL_INSTANCE_NAME}
      - CONTAINER_TIMEZONE=${TIMEZONE}
    volumes:
      - /tmp/isam-dev-lab/isam-volume:/var/shared
      - /tmp/isam-dev-lab/isam-logs/webseal:/var/application.logs
    ports:
      - "${WEBSEAL_HTTPS_PORT}:443"
      - "${WEBSEAL_HTTP_PORT}:80"
    depends_on:
        - isam-ldap
    cap_add:
      - SYS_PTRACE
      - SYS_RESOURCE

  isam-ldap:
    image: ibmcom/isam-openldap:latest
    hostname: isam-ldap
    environment:
      - LDAP_ADMIN_PASSWORD=${LDAP_PASSWORD}
      - LDAP_ENABLE_PORT_389=true
    volumes:
      - /tmp/isam-dev-lab/libldap:/var/lib/ldap
      - /tmp/isam-dev-lab/ldapslapd:/etc/ldap/slapd.d
      - /tmp/isam-dev-lab/libsecauthority:/var/lib/ldap.secAuthority
    ports:
      - ${LDAP_PORT}:389
     